# dependabot.yml file with customized schedule for version updates
# see https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "cargo"
    directory: "/"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "10:00"